// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnUfoQCHS2moC6V9qhZmtkiaoJ15Jrsrg',
    appId: '1:799536490688:web:705d147038c0f67e1c6525',
    messagingSenderId: '799536490688',
    projectId: 'dana-638e7',
    authDomain: 'dana-638e7.firebaseapp.com',
    storageBucket: 'dana-638e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1l94-AYQfjJhUttrGIu7NWD88QjyfVLs',
    appId: '1:799536490688:android:49d4412ce7159fd81c6525',
    messagingSenderId: '799536490688',
    projectId: 'dana-638e7',
    storageBucket: 'dana-638e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbUF7bzg_mHctXJK-kfEKRgUNTkcUyh1c',
    appId: '1:799536490688:ios:de5ae7a1cc8506101c6525',
    messagingSenderId: '799536490688',
    projectId: 'dana-638e7',
    storageBucket: 'dana-638e7.appspot.com',
    androidClientId: '799536490688-cmaqbglfu66p8i9fudhufpiu1rambqf9.apps.googleusercontent.com',
    iosClientId: '799536490688-od05jms0ui1jb9r3j7jqo8l1pi77igv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.end',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbUF7bzg_mHctXJK-kfEKRgUNTkcUyh1c',
    appId: '1:799536490688:ios:714a90e3184383151c6525',
    messagingSenderId: '799536490688',
    projectId: 'dana-638e7',
    storageBucket: 'dana-638e7.appspot.com',
    androidClientId: '799536490688-cmaqbglfu66p8i9fudhufpiu1rambqf9.apps.googleusercontent.com',
    iosClientId: '799536490688-d35ejd8jmqtqpge0hh2507lb9r65an5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.end.RunnerTests',
  );
}
